services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: klantroef_media
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  api:
    build: .
    environment:
      DATABASE_URL: mysql://root:root@db:3306/klantroef_media
      REDIS_URL: redis://redis:6379
      PORT: 5000
      JWT_SECRET: changeme
      STREAM_SECRET: changeme-stream
      UPLOAD_DIR: ./uploads
      BASE_URL: http://localhost:5000
    ports: ["5000:5000"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./uploads:/app/uploads
